# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "linked-list"
gem "rubytree"
gem 'get_process_mem'
gem 'murmurhash3'